name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: List Versions
        uses: cloudflare/wrangler-action@v3.7.0
        id: list_versions
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3.67.1'
          command: versions list --experimental-versions --env prod --json
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Get Latest Version ID
        id: get_latest_version
        run: echo "LATEST_VERSION=$(echo '${{ steps.list_versions.outputs.result }}' | jq -r '.[0].id')" >> $GITHUB_OUTPUT

      - name: Deploy Latest Version
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3.67.1'
          command: versions deploy ${{ steps.get_latest_version.outputs.LATEST_VERSION }}@100% --experimental-versions --env prod --message "${{ github.event.head_commit.message }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
