name: Deploy
on:
  push:
    branches:
      - main
jobs:
  upload-and-deploy:
    runs-on: ubuntu-latest
    name: Upload and Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3.67.1'
          command: --version

      - name: List and Deploy Latest Version
        run: |
          # List versions and get the latest version ID
          VERSIONS_JSON=$(npx wrangler versions list --experimental-versions --env prod --json)
          LATEST_VERSION=$(echo "$VERSIONS_JSON" | jq -r '.[0].id')
          echo "Latest version ID: $LATEST_VERSION"

          # Deploy the latest version
          npx wrangler versions deploy $LATEST_VERSION@100% --experimental-versions --env prod --message "${{ github.event.head_commit.message }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
